"""Agent settings. Everything is env-overridable with the ``UFO_AGENT_`` prefix.

Examples:
    UFO_AGENT_BACKEND=ufo
    UFO_AGENT_LOCAL_UI_PORT=9000
    UFO_AGENT_DATA_DIR=C:\\temp\\agent-data
"""

from __future__ import annotations

import platform
from pathlib import Path
from typing import Literal

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# Released exes embed their real version via agent/_buildinfo.py, generated by
# CI from the git tag (see .github/workflows/ci.yml). Source / editable installs
# fall back to a "-dev" version, which the frozen-only auto-update guard ignores.
try:
    from ._buildinfo import BUILD_VERSION as AGENT_VERSION
except ImportError:
    AGENT_VERSION = "0.1.0-dev"


class AgentSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="UFO_AGENT_", env_file=".env", extra="ignore")

    # Override the data directory (defaults to %LOCALAPPDATA%\UfoDeviceAgent on Windows).
    data_dir: Path | None = None

    # The local UI must stay loopback-only: it has no auth and can approve actions.
    local_ui_host: str = "127.0.0.1"
    local_ui_port: int = 8766

    # basic: real native Windows actions (default) | ufo: UFO² (milestone 2)
    backend: Literal["basic", "ufo"] = "basic"

    device_name: str = Field(default_factory=platform.node)

    heartbeat_seconds: float = 20.0
    reconnect_min_seconds: float = 1.0
    reconnect_max_seconds: float = 30.0
    approval_timeout_seconds: float = 600.0

    # --- auto-update (only ever runs from the frozen PyInstaller exe) ---
    # Hard kill-switch. Mandatory in CI's exe smoke test; useful for users who
    # manage updates externally. Source/dev runs are already inert (not frozen).
    disable_autoupdate: bool = False
    # GitHub repo to pull releases from: https://github.com/<update_repo>/releases
    update_repo: str = "posix4e/ufo-device-agent"
    update_max_attempts: int = 3  # per target version, before giving up to avoid boot loops
